### ISSUE TITLE
 Haskellkernel test in the latest Sel4 release on ubuntu 16.04-1 LTL (Xenial Xerus)

### ISSUE THREAD

**Issue by AmerTahat** [seL4/l4v#16]
Hi All,

First of all, i would to say , thanks a lot for Sel4 developers for their great job!

Next, I would like to share this experience and its solution. Probably, some people will find it useful. 

---
After running the test haskellkernel on ubuntu 16.04-1 LTL (Xenial Xerus) you may get this error:

> src/SEL4/Object/Interrupt.lhs-boot
cabal sandbox init
make: cabal: Command not found
Makefile:23: recipe for target 'build' failed
make: *** [build] Error 127

But after using  "curl -sSL https://get.haskellstack.org/ | sh " you may get another error like : 

TEST FAILED: HaskellKernel

cabal sandbox init
Writing a default package environment file to
/home/ssrgv/Desktop/verification/l4v/spec/haskell/cabal.sandbox.config
Creating a new sandbox at
/home/ssrgv/Desktop/verification/l4v/spec/haskell/.cabal-sandbox
cabal install --dependencies-only -w "ghc"
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: SEL4-ARM-1.4 (user goal)
next goal: base (dependency of SEL4-ARM-1.4)
rejecting: base-4.8.2.0/installed-0d6... (conflict: SEL4-ARM => base==4.7.*)
rejecting: base-4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0,
4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0,
4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global
constraint requires installed instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Makefile:23: recipe for target 'build' failed
make: *** [build] Error 1

Solution: So after running curl -sSL https://get.haskellstack.org/ | sh,  check the ghc version on your on ubuntu 16.04-1 LTL  (Xenial Xerus) machine, if it was 7.10.* then that might be the reason for the above error. 

Searching for a reason behind this indicated that ghc 7.10.* is currently unstable and sometimes does not work properly with cabal 1.22. So to use version cabal 1.20 and ghc 7.8.* together (as recommended in Sel4 pages) without problems on my machine I used the following steps:-

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:hvr/ghc
sudo apt-get update
sudo apt-get install -y cabal-install-1.20 ghc-7.8.3
cat >> ~/.bashrc <<EOF
export PATH=~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.3/bin:$PATH
EOF
export PATH=~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.3/bin:$PATH
cabal update
cabal install alex happy 
  --------------------------  

After this solution the test ran successfully! 

If someone ran into similar problem I hope you will find this discussion useful. 

Thanks!

**Comment by mbrcknl** [comment]
Hi, thanks for the report!

If my reading of this is correct, you are commenting that the Haskell kernel is quite picky about which versions of ghc and cabal-install you use, and in particular, that the versions supplied by many Linux distributions are unsuitable. You are certainly right about that. :-)

The reason for this is that our Haskell to Isabelle translator has been stuck in the past for some time, and despite some valiant efforts, we haven't yet managed to bring it up to date.

As you discovered, ghc-7.8.* and cabal-install-1.20 are the right versions.

Since it's quite inconvenient to maintain these old versions, we made a change to the Haskell kernel build to use the haskell-stack tool to obtain the right versions of ghc and cabal-install. You can see the change here:

https://github.com/seL4/l4v/commit/aee13996a609230ab010ed2bbb4f44060a603e11

So now, it should suffice to install a somewhat recent version of haskell-stack, available here:

https://docs.haskellstack.org/en/stable/install_and_upgrade/
