### ISSUE TITLE
Confusing version number for Abstract Specification

### ISSUE THREAD

**Issue by fidget324** [seL4/l4v#21]
The abstract specification *.pdf file generated by building the ASpec session is labeled with the seL4 API version number, which has not changed in the past four years. However, it seems that the abstract specification has undergone some substantial changes over that time period. I have encountered multiple seL4 specifications which are quite different from one another, yet list the same version number.

I found this confusing. Wouldn't it be better to label the abstract specification with the seL4 version number, e.g. 7.0.0?

**Comment by lsf37** [comment]
You are right, absolutely. It would be even better to automatically generate the PDF for each release.

It's been on our todo-list for a while, I'll bump up the priority.

**Comment by lsf37** [comment]
This is now addressed in e6c65356a06c78eac103cbe4cb4f6798c215cfea, at least to the degree that PDF generation will now automatically include the seL4 version and repository hash from which the document is generated.

The PDF is still not automatically generated and published to the website for point releases. Since that's really a separate issue, I think we can close this one.

Do you agree?

**Comment by fidget324** [comment]
Yes and yes. Adding the commit hash is a nice touch. Thanks!
