### ISSUE TITLE
Question: Is Owicki-Gries's Hoare logic used in seL4 verification?

### ISSUE THREAD

**Issue by adrianastancu471** [seL4/l4v#246]
I am fairly new to Isabelle, I recently found out that Owicki-Gries's Hoare logic is implemented in Isabelle/HO - Hoare_Parallel theory.

In sel4, I thought that the same theory would be used for most of the kernel components but cannot find this theory used in any of the sel4 lemmas.

For example, taking the interrupts intro consideration, the "irq_timer" is enabled for x86 processors, but crefine/x86 theories don't mention using the OG logic.

My question is how the interrupts, endpoints or any other form of concurrency and synchronization is handled in sel4?
If you can point some documentation or the related theories in this repo, I would be grateful.

**Comment by mbrcknl** [comment]
Currently, the bulk of the proofs about seL4 are for single-core configurations, i.e. without any parallelism. For the [abstract](https://github.com/seL4/l4v/tree/dd6529f520a25328469fc44cfd54f3b29ffd75cc/spec/abstract) and [intermediate](https://github.com/seL4/l4v/tree/dd6529f520a25328469fc44cfd54f3b29ffd75cc/spec/haskell) specifications, they use a [simpler Hoare logic](https://github.com/seL4/l4v/blob/dd6529f520a25328469fc44cfd54f3b29ffd75cc/lib/Monad_WP/NonDetMonad.thy#L729-L754) for a [non-deterministic state monad](https://github.com/seL4/l4v/blob/dd6529f520a25328469fc44cfd54f3b29ffd75cc/lib/Monad_WP/NonDetMonad.thy#L26-L35). For the C, we have a [C parser](https://github.com/seL4/l4v/tree/dd6529f520a25328469fc44cfd54f3b29ffd75cc/tools/c-parser) which embeds the C semantics in [Norbert Schirmer's SIMPL](https://github.com/seL4/l4v/tree/dd6529f520a25328469fc44cfd54f3b29ffd75cc/tools/c-parser/Simpl), which has it's own [Hoare logic](https://github.com/seL4/l4v/blob/dd6529f520a25328469fc44cfd54f3b29ffd75cc/tools/c-parser/Simpl/HoarePartialDef.thy#L230-L286).

We've made some progress towards proofs for multi-core seL4, but this is still work in progress. IIUC, that work replaces the state monad with a trace monad, and SIMPL is replaced with [COMPLX](https://ts.data61.csiro.au/publications/csiro_full_text/Amani_ABLRT_17.pdf). I believe the Hoare logic is replaced with Owicki-Gries. @lsf37 and @corlewis should be able to say more.

**Comment by lsf37** [comment]
The COMPLX language currently supports Owicki-Gries, and it worked fine for smaller projects like the eChronos RTOS we used it for, but for the large code base in seL4 and the refinement approach we have there it is unlikely that we'll use it. The thinking currently is going more towards variants of Rely-Guarantee reasoning for that.

**Comment by lsf37** [comment]
To address the implicit part of the question: how do interrupts and other apparently concurrent things work in seL4?

The answer is that seL4 is designed to not have any internal concurrent execution at all. Interrupts are off during kernel execution, and system calls on unicore machines (that the proof applies to) are sequential. To achieve low latency, the kernel checks in long-running operations (of which there are few) wether an interrupt has occurred at specific preemption points. If one did occur, the state of the work done so far is saved, the current kernel call ends, and a new system call (IRQ kernel entry) starts. The PC of the invoker of the old system call is reset so that the old system call will be restarted when that user thread gets scheduled again.

This means, the bulk of the seL4 proofs are sequential, as Matt described. The plans for multicore proofs do involve concurrency logics, but even though there has been a lot of background work, the actual seL4 verification there has not started yet.

**Comment by adrianastancu471** [comment]
Thank you for the quick and detailed response! I am interested in verification of isolated drivers and naturally stumbled upon concurrency. I will also check out the work done for eChronos RTOS and close this issue.
