### ISSUE TITLE
Question: Fail to parse function pointers

### ISSUE THREAD

**Issue by adrianastancu471** [seL4/l4v#268]
I am trying to parse a program that uses function pointers, they are only void functions that returns void, arguments are modified through global variables.

Basically there is only a function pointer that can be set to a given routine, in the example below I set it to point to foo() function, but still there is not enough data to ensure that only the global variables are modified?
```
static int counter;

void foo(void) {
	counter++;
}

void (*p_fun)(void);

void set_function(void) {
	p_fun = foo;
}

void call_function(void) {
	if(p_fun) p_fun();
}

`Tactic failed 
The error(s) above occurred for the goal statement⌂:
∀σ. Γ⊢⇘/UNIV⇙ {σ} Call foo_'proc
               {t. t may_only_modify_globals σ in [counter]`

**Comment by lsf37** [comment]
The problem may actually be in the `static int` declaration for `counter`.

I assume the command that is failing is `install_C_file`. Does it still fail with just the following program?
```C
static int counter;

void foo(void) {
	counter++;
}
```
If yes, does it work if you remove `static`?

**Comment by adrianastancu471** [comment]
Yes, it is falling at `install_C_file`, the program above can be parsed successfully with static int declaration.
In my program, the part that fails is the function call from  `call_function` if I comment out the line
```	
if(p_fun) p_fun();
```
the program can be parsed. I think it cannot prove that the function pointer assigned modifies only globals variables, because the `p_fun` can be a pointer to any function.

**Comment by lsf37** [comment]
Yes, you are probably right. I just got confused by the error message being about `foo`, which is pretty much the only function it should be able to figure out.

There could theoretically be enough information in the program for the parser to figure out that `p_fun` can only be `foo` or nothing, but I doubt that it actually will. @mn200 is currently away, I think, but he might remember more about how this particular analysis works.

**Comment by mn200** [comment]
I'm afraid I cannot remember at all what is done by way of `modifies` analysis for function pointers.  I assume it is maximally pessimistic and assumes that it might touch anything (this is the easy, safe, approach).

**Comment by mbrcknl** [comment]
This does seem rather strange, for two reasons:
- The goal in the error message should be easily provable. The modifies prover would routinely prove hundreds of goals just like this one while parsing seL4. So why is it claiming this goal is not provable?
- The offending statement doesn't mention `foo` at all. Indeed, there is no call to `foo` anywhere in the source. So why do we end up with this goal in the first place?

**Comment by adrianastancu471** [comment]
There is a call to `foo` function, but it is done through the function pointer `p_fun();` which is set to `foo()`'s address. 

But I could also set p_fun to point to any other address so it might not have enough information to be sure that `p_fun` function pointer is set only once in `set_function` and it is always equal with `foo` address. 

Is there a way to indicate the the function foo() is static linked (I want to point out that the function will alway be at the same address so p_fun will always point to it), or maybe it does not matter for C parser.

**Comment by mbrcknl** [comment]
I had a quick look at this. I think the error message in the original issue must be for a different program than the one quoted.

I found that with this program:
```C
int (*p_fun)(int);
int global_int;

int do_nothing(int i) {
  return i;
}

int do_something(int i) {
  global_int += i;
  return global_int;
}

void set_function(void) {
  p_fun = do_nothing;
}

void call_function(void) {
  if (p_fun) p_fun();
}
```
I get this error:
```
Tactic failed
The error(s) above occurred for the goal statement⌂:
∀σ. Γ⊢⇘/UNIV⇙ {σ} Call call_function_'proc {t. t may_only_modify_globals σ in [global_int]} 
```
That error makes much more sense to me. In particular, it's a goal about `call_function`, which is the one that contains the call through a function pointer.

It turns out that the C parser handles function pointers quite nicely, in that it generates sensible `modifies` theorems. It's not maximally pessimistic as @mn200 thought it might be. It appears to calculate the potentially modified global variables based on the *type* of the function pointer. In my example above, the type of `p_fun` is `int(int)`. There are two functions of that type, and altogether, the only global they modify is `global_int`. Therefore, the modifies theorem for `call_function` says that `call_function` may modify `global_int`. But note that `call_function` may *not* modify `p_fun`. The C parser has calculated that there are no ways to get from any function of type `int(int)` to a site where `p_fun` is modified (which is only in `set_function`).

The problem is just that the Simpl VCG (verification condition generator) that the C parser uses to prove these `modifies` theorems is not able to handle the way calls through function pointers are specified.

I'm not sure what to do about this yet. If I find a bit more time, I'll try proving the `modifies` theorem manually, and then see if the approach can be generalised to add to the modifies prover.

The only workaround I can think of is to add:
```
declare [[calculate_modifies_proofs = false]]
```
before the `install_C_file`. But this is a big hammer, in that it means you won't get any `modifies` theorems out of the C parser. You would have to prove them yourself if you need them. This is a safe hammer, but potentially annoying.

If you trust the C parser to calculate only sound/true modifies theorems, you could alternatively ask it to assert those theorems as axioms rather than try to prove them:
```
declare [[quick_and_dirty = true]]
declare [[sorry_modifies_proofs = true]]

external_file "foo.c"
install_C_file "foo.c"

declare [[quick_and_dirty = false]]
```
This is also a big hammer, but this one is dangerous.

**Comment by mbrcknl** [comment]
> Is there a way to indicate the the function foo() is statically linked (I want to point out that the function will always be at the same address so p_fun will always point to it), or maybe it does not matter for C parser.

I don't think the C parser has any specific support for that. To do that soundly, you would need to prove something like an invariant over the main part of your program. The condition would be established by `set_function`, and you would need to *prove* that the condition is maintained from that point to any call to `call_function`. Under that condition, you could show that `call_function` is then equivalent to the function that was set up in `set_function`. This is fundamentally dynamic, so there's no shortcut if you want proof that your dynamic setup behaves as if it was static.

You could axiomatise the behaviour of `call_function`, but you would have to be very careful to avoid ending up with something unsound.

If you're sure that you only ever call `call_function` when `p_fun` points to some function `foo`, then there are ways to axiomatise that. You would first add this instruction to the C parser just above `call_function`:
```
/** DONT_TRANSLATE */
```
This tells the C parser not to look at the body of the function. You can then axiomatise the behaviour of `call_function` to be the same as

**Comment by adrianastancu471** [comment]
I think all my questions were answered in the previous comments. Thank you for your help and the detailed explanations!
