### ISSUE TITLE
Question: Some problems encountered when using Isabelle to create a new rule base

### ISSUE THREAD

**Issue by Wang-zw** [seL4/l4v#277]
Recently, I encountered some problems while studying Isabelle. Is there any great god who can help me solve them?Thank you.

1. When I try to create a new rule base, copy the Ex exist quantifier that has been defined in "Isabelle2017\src\HOL\HOL.thy", it will report an error, and use code_Q for mapping will also report an error.

2. "Isabelle2017\src\HOL\HOL.thy" is a built-in rule, why will it report an error when it is opened?

![1-1](https://user-images.githubusercontent.com/46117841/116549664-597bbe80-a928-11eb-9237-88ec3e9c284e.png)
![1-2](https://user-images.githubusercontent.com/46117841/116549673-5b458200-a928-11eb-822f-701bb70f587b.png)
![2](https://user-images.githubusercontent.com/46117841/116549676-5bde1880-a928-11eb-9de6-9897ccda72a9.png)

**Comment by lsf37** [comment]
This is not really a question about the seL4 proofs, and therefore not appropriate for this issue tracker. You should ask it on the [Isabelle mailing list](https://lists.cam.ac.uk/mailman/listinfo/cl-isabelle-users) or on [Isabelle stackoverflow](https://stackoverflow.com/questions/tagged/isabelle)

The short answer is, if you copy the definition of `Ex` from `HOL` the name and syntax is already taken by the one from `HOL`. The name is less critical, because Isabelle will resolve that with a qualified name (yours will be called `Newmethod.Ex`, but it can't do that for the syntax part (the `binder ...` declaration). You'll have to pick a different symbol for it to work.

In general it's not advisable to define your own existential quantifier and logical connectives, you'd only do that for very special circumstances. Usually you can use the ones that are already there.

**Comment by Wang-zw** [comment]
Thank you, your suggestion is of great reference value to me. And I’m sorry, this is the first time I have asked a question in the community, so I came to the wrong place to post a question.

**Comment by Wang-zw** [comment]
> This is not really a question about the seL4 proofs, and therefore not appropriate for this issue tracker. You should ask it on the [Isabelle mailing list](https://lists.cam.ac.uk/mailman/listinfo/cl-isabelle-users) or on [Isabelle stackoverflow](https://stackoverflow.com/questions/tagged/isabelle)
> 
> The short answer is, if you copy the definition of `Ex` from `HOL` the name and syntax is already taken by the one from `HOL`. The name is less critical, because Isabelle will resolve that with a qualified name (yours will be called `Newmethod.Ex`, but it can't do that for the syntax part (the `binder ...` declaration). You'll have to pick a different symbol for it to work.
> 
> [edit: it's actually the `All` quantifier that Isabelle gets confused about in the definition of `Ex`, for the reasons described above. That is, when Isabelle sees the right-hand side of the `Ex` definition, it doesn't know which `All` syntax it should apply. If you change the syntax symbols (for all of them), the definitions should work]
> 
> In general it's not advisable to define your own existential quantifier and logical connectives, you'd only do that for very special circumstances. Usually you can use the ones that are already there.

Thank you, your suggestion is of great reference value to me. And I’m sorry, this is the first time I have asked a question in the community, so I came to the wrong place to post a question.

**Comment by lsf37** [comment]
No worries. Stack overflow is a good place for these.
