### ISSUE TITLE
psutil methods with get_ prefix are deprecated

### ISSUE THREAD

**Issue by cmr** [seL4/l4v#5]
psutil as of 2.0.0 renamed all getters to avoid the `get_` prefix, in March 2014, leaving behind a deprecation warning.

The 3.0.0 release in June this year removed them.

Unfortunately, Ubuntu/Debian still ship an ancient psutil version. Other Linux distros are using the new version, and the new versions are what can be obtained from pip. I'm not sure what the best way forward is here.

**Comment by Smattr** [comment]
Thanks for the issue report. I'm not sure exactly which file(s) this issue relates to, so I'm going to assume you're talking about the [memusage util](https://github.com/seL4/l4v/blob/master/misc/regression/memusage.py). The regression tests try to work around this API change in [other places](https://github.com/seL4/l4v/blob/master/misc/regression/run_tests.py#L39-L40), but if we need to keep doing this we should probably have a unified psutil wrapper. I suspect no one has reported this internally because many users do not have psutil installed and our servers are pinned to specific psutil versions.
