### ISSUE TITLE
'nslookup' tool missing while executing "./build.sh -b l4v"

### ISSUE THREAD

**Issue by GooTal** [seL4/l4v#514]
I cloned this repo and executed this command "./build.sh -b l4v", then got message :
```
.....
cabal-install    > Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.4.1.0/build/cabal/cabal ...
cabal-install    > copy/register
cabal-install    > Installing executable cabal in /root/.stack/snapshots/x86_64-linux-tinfo6/f04d0d45be1db2d1a4535c7134bb900ee49fac5cd84a673d5abb9a8554c6afdd/9.0.2/bin
Completed 22 action(s).
stack exec -- ./stack-path cabal v2-update
Config file path source is default config file.
Config file /root/.cabal/config not found.
Writing default configuration to /root/.cabal/config
Warning: 'nslookup' tool missing - can't locate mirrors
```
I waited for an hour and it seems stucked here. 

So i added `dnsutils` in `scripts/l4v.sh` and got no warning about nslookup. But it still stucked here:
```
.....
cabal-install    > Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.4.1.0/build/cabal/cabal ...
cabal-install    > copy/register
cabal-install    > Installing executable cabal in /root/.stack/snapshots/x86_64-linux-tinfo6/f04d0d45be1db2d1a4535c7134bb900ee49fac5cd84a673d5abb9a8554c6afdd/9.0.2/bin
Completed 22 action(s).
stack exec -- ./stack-path cabal v2-update
Config file path source is default config file.
Config file /root/.cabal/config not found.
Writing default configuration to /root/.cabal/config
```

Did I miss something? Any idea to solve this problem?  Thanks a lot.

**Comment by lsf37** [comment]
Hi @GooTal -- there is no `build.sh` command in this repo. Are you working on the [docker container repo](https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles)?

The scripts in there are meant to run inside the container, and `dnsutils` should definitely be installed there (the containers are built regularly and the `l4v` build seems to be working). Instead of building it, you can also pull the container [from docker directly](https://hub.docker.com/r/trustworthysystems/l4v).

**Comment by GooTal** [comment]
Oh, thank you.
I can`t recall the details about this problem. But i remember solving this problem by adding 'sudo' command. It took me quite long time because i was not quite familiar with cabal. Anyway, the problem solved.

**Comment by lsf37** [comment]
No worries, glad it worked in the end.
